-- Season 3 socketed PVP armor (verified sockets only)
GemOrder_PvpGear = {
    { name = "Vengeful Gladiator's Chain Armor", itemId = 33664, sockets = "2 Red, 1 Yellow", category = "PVP", class = "Hunter" },
    { name = "Vengeful Gladiator's Chain Helm", itemId = 33666, sockets = "1 Meta, 1 Red", category = "PVP", class = "Hunter" },
    { name = "Vengeful Gladiator's Chain Spaulders", itemId = 33668, sockets = "1 Red, 1 Yellow", category = "PVP", class = "Hunter" },
    { name = "Vengeful Gladiator's Dragonhide Helm", itemId = 33672, sockets = "1 Meta, 1 Yellow", category = "PVP", class = "Druid" },
    { name = "Vengeful Gladiator's Dragonhide Spaulders", itemId = 33674, sockets = "1 Red, 1 Yellow", category = "PVP", class = "Druid" },
    { name = "Vengeful Gladiator's Dragonhide Tunic", itemId = 33675, sockets = "2 Red, 1 Yellow", category = "PVP", class = "Druid" },
    { name = "Vengeful Gladiator's Dreadweave Hood", itemId = 33677, sockets = "1 Meta, 1 Red", category = "PVP", class = "Warlock" },
    { name = "Vengeful Gladiator's Dreadweave Mantle", itemId = 33679, sockets = "1 Blue, 1 Yellow", category = "PVP", class = "Warlock" },
    { name = "Vengeful Gladiator's Dreadweave Robe", itemId = 33680, sockets = "1 Red, 2 Yellow", category = "PVP", class = "Warlock" },
    { name = "Vengeful Gladiator's Felweave Amice", itemId = 33682, sockets = "1 Blue, 1 Yellow", category = "PVP", class = "Warlock" },
    { name = "Vengeful Gladiator's Felweave Cowl", itemId = 33683, sockets = "1 Meta, 1 Red", category = "PVP", class = "Warlock" },
    { name = "Vengeful Gladiator's Felweave Raiment", itemId = 33685, sockets = "1 Red, 2 Yellow", category = "PVP", class = "Warlock" },
    { name = "Vengeful Gladiator's Kodohide Helm", itemId = 33691, sockets = "1 Meta, 1 Yellow", category = "PVP", class = "Druid" },
    { name = "Vengeful Gladiator's Kodohide Spaulders", itemId = 33693, sockets = "1 Red, 1 Yellow", category = "PVP", class = "Druid" },
    { name = "Vengeful Gladiator's Kodohide Tunic", itemId = 33694, sockets = "2 Red, 1 Yellow", category = "PVP", class = "Druid" },
    { name = "Vengeful Gladiator's Lamellar Chestpiece", itemId = 33695, sockets = "2 Red, 1 Yellow", category = "PVP", class = "Paladin" },
    { name = "Vengeful Gladiator's Lamellar Helm", itemId = 33697, sockets = "1 Meta, 1 Red", category = "PVP", class = "Paladin" },
    { name = "Vengeful Gladiator's Lamellar Shoulders", itemId = 33699, sockets = "1 Red, 1 Yellow", category = "PVP", class = "Paladin" },
    { name = "Vengeful Gladiator's Leather Helm", itemId = 33701, sockets = "1 Meta, 1 Red", category = "PVP", class = "Rogue" },
    { name = "Vengeful Gladiator's Leather Spaulders", itemId = 33703, sockets = "1 Red, 1 Yellow", category = "PVP", class = "Rogue" },
    { name = "Vengeful Gladiator's Leather Tunic", itemId = 33704, sockets = "2 Red, 1 Yellow", category = "PVP", class = "Rogue" },
    { name = "Vengeful Gladiator's Linked Armor", itemId = 33706, sockets = "2 Red, 1 Yellow", category = "PVP", class = "Shaman" },
    { name = "Vengeful Gladiator's Linked Helm", itemId = 33708, sockets = "1 Meta, 1 Red", category = "PVP", class = "Shaman" },
    { name = "Vengeful Gladiator's Linked Spaulders", itemId = 33710, sockets = "1 Red, 1 Yellow", category = "PVP", class = "Shaman" },
    { name = "Vengeful Gladiator's Mail Armor", itemId = 33711, sockets = "1 Red, 2 Yellow", category = "PVP", class = "Shaman" },
    { name = "Vengeful Gladiator's Mail Helm", itemId = 33713, sockets = "1 Meta, 1 Red", category = "PVP", class = "Shaman" },
    { name = "Vengeful Gladiator's Mail Spaulders", itemId = 33715, sockets = "1 Red, 1 Yellow", category = "PVP", class = "Shaman" },
    { name = "Vengeful Gladiator's Mooncloth Hood", itemId = 33718, sockets = "1 Meta, 1 Red", category = "PVP", class = "Priest" },
    { name = "Vengeful Gladiator's Mooncloth Mantle", itemId = 33720, sockets = "1 Red, 1 Yellow", category = "PVP", class = "Priest" },
    { name = "Vengeful Gladiator's Mooncloth Robe", itemId = 33721, sockets = "1 Red, 2 Yellow", category = "PVP", class = "Priest" },
    { name = "Vengeful Gladiator's Ornamented Chestguard", itemId = 33722, sockets = "2 Red, 1 Yellow", category = "PVP", class = "Paladin" },
    { name = "Vengeful Gladiator's Ornamented Headcover", itemId = 33724, sockets = "1 Meta, 1 Red", category = "PVP", class = "Paladin" },
    { name = "Vengeful Gladiator's Ornamented Spaulders", itemId = 33726, sockets = "1 Red, 1 Yellow", category = "PVP", class = "Paladin" },
    { name = "Vengeful Gladiator's Plate Chestpiece", itemId = 33728, sockets = "2 Red, 1 Yellow", category = "PVP", class = "Warrior" },
    { name = "Vengeful Gladiator's Plate Helm", itemId = 33730, sockets = "1 Meta, 1 Yellow", category = "PVP", class = "Warrior" },
    { name = "Vengeful Gladiator's Plate Shoulders", itemId = 33732, sockets = "1 Red, 1 Yellow", category = "PVP", class = "Warrior" },
    { name = "Vengeful Gladiator's Ringmail Armor", itemId = 33738, sockets = "1 Red, 2 Yellow", category = "PVP", class = "Shaman" },
    { name = "Vengeful Gladiator's Ringmail Helm", itemId = 33740, sockets = "1 Meta, 1 Red", category = "PVP", class = "Shaman" },
    { name = "Vengeful Gladiator's Ringmail Spaulders", itemId = 33742, sockets = "1 Red, 1 Yellow", category = "PVP", class = "Shaman" },
    { name = "Vengeful Gladiator's Satin Hood", itemId = 33745, sockets = "1 Meta, 1 Red", category = "PVP", class = "Priest" },
    { name = "Vengeful Gladiator's Satin Mantle", itemId = 33747, sockets = "1 Red, 1 Yellow", category = "PVP", class = "Priest" },
    { name = "Vengeful Gladiator's Satin Robe", itemId = 33748, sockets = "1 Red, 2 Yellow", category = "PVP", class = "Priest" },
    { name = "Vengeful Gladiator's Scaled Chestpiece", itemId = 33749, sockets = "2 Red, 1 Yellow", category = "PVP", class = "Paladin" },
    { name = "Vengeful Gladiator's Scaled Helm", itemId = 33751, sockets = "1 Meta, 1 Red", category = "PVP", class = "Paladin" },
    { name = "Vengeful Gladiator's Scaled Shoulders", itemId = 33753, sockets = "1 Red, 1 Yellow", category = "PVP", class = "Paladin" },
    { name = "Vengeful Gladiator's Silk Amice", itemId = 33757, sockets = "1 Blue, 1 Yellow", category = "PVP", class = "Mage" },
    { name = "Vengeful Gladiator's Silk Cowl", itemId = 33758, sockets = "1 Meta, 1 Red", category = "PVP", class = "Mage" },
    { name = "Vengeful Gladiator's Silk Raiment", itemId = 33760, sockets = "1 Red, 2 Yellow", category = "PVP", class = "Mage" },
    { name = "Vengeful Gladiator's Wyrmhide Helm", itemId = 33768, sockets = "1 Meta, 1 Yellow", category = "PVP", class = "Druid" },
    { name = "Vengeful Gladiator's Wyrmhide Spaulders", itemId = 33770, sockets = "1 Red, 1 Yellow", category = "PVP", class = "Druid" },
    { name = "Vengeful Gladiator's Wyrmhide Tunic", itemId = 33771, sockets = "2 Red, 1 Yellow", category = "PVP", class = "Druid" },
    { name = "Vindicator's Dragonhide Bracers", itemId = 33881, sockets = "1 Red", category = "PVP", class = "Druid" },
    { name = "Vindicator's Dreadweave Cuffs", itemId = 33883, sockets = "1 Yellow", category = "PVP", class = "Warlock" },
    { name = "Vindicator's Kodohide Bracers", itemId = 33887, sockets = "1 Red", category = "PVP", class = "Druid" },
    { name = "Vindicator's Lamellar Bracers", itemId = 33889, sockets = "1 Yellow", category = "PVP", class = "Paladin" },
    { name = "Vindicator's Leather Bracers", itemId = 33893, sockets = "1 Yellow", category = "PVP", class = "Rogue" },
    { name = "Vindicator's Linked Bracers", itemId = 33894, sockets = "1 Yellow", category = "PVP", class = "Shaman" },
    { name = "Vindicator's Mail Bracers", itemId = 33897, sockets = "1 Yellow", category = "PVP", class = "Hunter" },
    { name = "Vindicator's Mooncloth Cuffs", itemId = 33901, sockets = "1 Yellow", category = "PVP", class = "Priest" },
    { name = "Vindicator's Ornamented Bracers", itemId = 33904, sockets = "1 Yellow", category = "PVP", class = "Paladin" },
    { name = "Vindicator's Ringmail Bracers", itemId = 33906, sockets = "1 Yellow", category = "PVP", class = "Shaman" },
    { name = "Vindicator's Scaled Bracers", itemId = 33910, sockets = "1 Yellow", category = "PVP", classes = { "Warrior", "Paladin" } },
    { name = "Vindicator's Silk Cuffs", itemId = 33913, sockets = "1 Yellow", category = "PVP", class = "Mage" },
    { name = "Vindicator's Wyrmhide Bracers", itemId = 33917, sockets = "1 Red", category = "PVP", class = "Druid" },
}
